apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: eu.gcr.io/support-trainer-vmucuge/echo:v1
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: "1"
