---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  templates:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
      - containerPort: 80
