apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-webapp-v2
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: webapp
        version: v2
        environment: prod
        tier: fe
    spec:
      containers:
      - name: webapp-v2
        image: eu.gcr.io/support-trainer-vmucuge/webapp:v2
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /ok
            port: 8888
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
