apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbook-v1
spec:
  replicas: 10
  selector:
    name: guestbook-v1
  template:
    metadata:
      labels:
        name: guestbook-v1
        version: "v1.0"
      name: guestbook-v1
    spec:
      containers:
      - imagePullPolicy: Always
        image: gcr.io/support-trainer-vmucuge/guestbook:1.0
        name: guestbook
        env:
        - name: MONGO_HOST
          value: "mongodb-1" # Service name mongodb here
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: "guestbook"
        - name: MONGO_USER
          value: "guestbook"
        - name: MONGO_PASSWORD
          value: "guestbook123"
        # Checks when the container is ready.
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        # Checks if the container is still alive.
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
