apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-1
spec:
  replicas: 1
  selector:
    name: mongodb-1
  template:
    metadata:
      labels:
        name: mongodb-1
        db: mongodb
      name: mongodb-1
    spec:
      containers:
      - imagePullPolicy: Always
        image: mongo:3
        name: mongodb
        args:
         - "mongod"
         - "--replSet"
         - "rs-minefield"
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
      volumes:
        # This GCE PD must already exist. Read README for more information
      - name: mongodb-data
        gcePersistentDisk:
          pdName: mongodb-pd-1
          fsType: ext4
