apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: jenkins
        version: v1
        environment: dev
        tier: ci
    spec:
      containers:
      - name: jenkins
        imagePullPolicy: Always
        image: eu.gcr.io/support-trainer-vmucuge/jenkins
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
