apiVersion: v1
kind: ReplicationController
metadata:
  name: lostnocost
spec:
  replicas: 2
  selector:
    name: lostnocost
  template:
    metadata:
      labels:
        name: lostnocost
        version: "0.1"
      name: lostnocost
    spec:
      containers:
      - imagePullPolicy: Always
        image: nginx
        name: lostnocost
        env:
        - name: WEBAPP
          value: "lostnocost"
        # Checks when the container is ready.
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        # Checks if the container is still alive.
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
